Add missing snapshot() quality parameter
I got `TypeError: snapshot() got an unexpected keyword argument 'quality'` trying to use `touch(Template('image.png'))` on linux.